-- Aisles operational data. Server code connects through Hyperdrive in
-- Cloudflare and directly with DATABASE_URL for local and Node-script use;
-- no anon/authenticated grants or RLS policies are created here.

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

CREATE TABLE public.enriched_products (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id         TEXT NOT NULL,
  bc_entity_id     INTEGER NOT NULL,
  bc_product_path  TEXT NOT NULL,
  material         TEXT,
  style            TEXT,
  use_case         TEXT,
  dimensions       TEXT,
  price_tier       TEXT CHECK (price_tier IN ('budget', 'mid', 'premium', 'luxury')),
  fit_gatherer     REAL NOT NULL DEFAULT 0.5,
  fit_hunter       REAL NOT NULL DEFAULT 0.5,
  fit_researcher   REAL NOT NULL DEFAULT 0.5,
  fit_gifter       REAL NOT NULL DEFAULT 0.5,
  semantic_tags    TEXT[] NOT NULL DEFAULT '{}',
  compatible_with  TEXT[] NOT NULL DEFAULT '{}',
  embedding        extensions.vector(1536),
  enriched_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  enrichment_model TEXT NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (brand_id, bc_entity_id)
);

CREATE INDEX enriched_products_brand_entity_idx ON public.enriched_products (brand_id, bc_entity_id);
CREATE INDEX enriched_products_semantic_tags_idx ON public.enriched_products USING GIN (semantic_tags);

CREATE TABLE public.generation_logs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id        TEXT NOT NULL,
  type            TEXT NOT NULL,
  persona         TEXT NOT NULL,
  category_slug   TEXT NOT NULL,
  cache_hit       BOOLEAN NOT NULL DEFAULT FALSE,
  generation_ms   INTEGER NOT NULL,
  product_count   INTEGER,
  input_tokens    INTEGER,
  output_tokens   INTEGER,
  eval_score      REAL,
  prompt_version  TEXT DEFAULT 'v1',
  model           TEXT,
  estimated_cost  REAL,
  session_id      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX generation_logs_brand_created_idx ON public.generation_logs (brand_id, created_at DESC);
CREATE INDEX generation_logs_brand_session_idx ON public.generation_logs (brand_id, session_id) WHERE session_id IS NOT NULL;

CREATE TABLE public.session_outcomes (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id              TEXT NOT NULL,
  session_id            TEXT NOT NULL,
  ended_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  duration_ms           BIGINT NOT NULL DEFAULT 0,
  primary_final         TEXT NOT NULL CHECK (primary_final IN ('gatherer', 'hunter', 'researcher', 'gifter')),
  probabilities_final   JSONB NOT NULL,
  entropy_final         REAL NOT NULL,
  certainty_final       REAL NOT NULL,
  prior_at_start        JSONB NOT NULL,
  converted             BOOLEAN NOT NULL DEFAULT FALSE,
  cart_add_count        INTEGER NOT NULL DEFAULT 0,
  cart_removal_count    INTEGER NOT NULL DEFAULT 0,
  product_view_count    INTEGER NOT NULL DEFAULT 0,
  category_view_count   INTEGER NOT NULL DEFAULT 0,
  refine_message_count  INTEGER NOT NULL DEFAULT 0,
  back_nav_count        INTEGER NOT NULL DEFAULT 0,
  max_scroll_depth      REAL NOT NULL DEFAULT 0,
  avg_dwell_ms          REAL NOT NULL DEFAULT 0,
  visit_count           INTEGER NOT NULL DEFAULT 1,
  current_category      TEXT,
  rule_matches          TEXT[] NOT NULL DEFAULT '{}',
  label_source          TEXT NOT NULL DEFAULT 'unknown',
  label_persona         TEXT CHECK (label_persona IN ('gatherer', 'hunter', 'researcher', 'gifter') OR label_persona IS NULL),
  UNIQUE (brand_id, session_id)
);

CREATE INDEX session_outcomes_brand_ended_idx ON public.session_outcomes (brand_id, ended_at DESC);
CREATE INDEX session_outcomes_brand_label_idx ON public.session_outcomes (brand_id, label_source) WHERE label_source <> 'unknown';
CREATE INDEX session_outcomes_brand_primary_idx ON public.session_outcomes (brand_id, primary_final);

CREATE TABLE public.merchandising_rules (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id      TEXT NOT NULL,
  store_hash    TEXT NOT NULL,
  rule_type     TEXT NOT NULL CHECK (rule_type IN ('pin', 'exclude', 'boost', 'seasonal')),
  persona       TEXT,
  category_slug TEXT,
  product_id    TEXT,
  config        JSONB NOT NULL,
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  starts_at     TIMESTAMPTZ,
  expires_at    TIMESTAMPTZ,
  created_by    TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX merchandising_rules_brand_active_idx ON public.merchandising_rules (brand_id, active, created_at DESC);

ALTER TABLE public.enriched_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.generation_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.merchandising_rules ENABLE ROW LEVEL SECURITY;
